version: 2

models:
  - name: fact_match
    columns:
      - name: match_id
        tests:
          - unique
          - not_null
      
      - name: home_team_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_team')
              field: team_key

      - name: away_team_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_team')
              field: team_key
        
      
      